---
- name: Starting and Enabling httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Starting and Enabling apache2
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == 'Debian' or when: ansible_distribution == 'Ubuntu'


